### PR TITLE
migrate from TravisCI to GitHub Actions

### PR DESCRIPTION
**Pull request by jelhan**
GitHub Actions configuration was created with [create-github-actions-setup-for-ember-addon](https://github.com/jelhan/create-github-actions-setup-for-ember-addon). Haven't noticed anything special in existing TravisCI configuration. So it should work out of the box. But please double check before merging.

### CODE REVIEW

**Comment by pzuraq** [comment]
It seems like the action wasn't triggered for this PR, which is a bit concerning. Do we need to enable actions somehow? Normally they Just Work™️ in my experience

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Lets see what happens...

**Comment by jelhan** [comment]
> Lets see what happens...

Thanks for the trust. :sweat_smile:

Merging triggered this CI pipeline for `master` branch: https://github.com/ember-modifier/ember-modifier/runs/2326155181 Looks good so far, isn't it?

**Comment by rwjblue** [comment]
Yep, seems like things are good!

**Pull request merged**
