### PR TITLE
Update class-based modifier in blueprint

### PR DESCRIPTION
**Pull request by bertdeblock**
_Juuust_ a little less typing and more in line with the functional one.

### CODE REVIEW

**Review by SergeAstapov — APPROVED** [review]

**Review by chriskrycho — APPROVED** [review]

**Comment by chriskrycho** [comment]
@bertdeblock or @SergeAstapov do you have time to back-port this to the v3 branch? If not, I'll try to do so late this week.

**Comment by SergeAstapov** [comment]
@chriskrycho done in https://github.com/ember-modifier/ember-modifier/pull/315

**Comment by SergeAstapov** [comment]
and it's included in #296!

**Comment by SergeAstapov** [comment]
and created similar PR https://github.com/ember-modifier/ember-modifier/pull/316 for function-based modifiers for v3

**Pull request merged**
