### PR TITLE
Properly re-export types

### PR DESCRIPTION
**Pull request by mydea**
This PR moves type-only modules to be `.d.ts` instead of `.ts` and uses `export type` to re-export them, avoiding warnings in Embroider.

Closes https://github.com/ember-modifier/ember-modifier/issues/128

### CODE REVIEW

**Comment by mydea** [comment]
Any chance to get this reviewed/merged, would be nice to clean up the build output of our app a bit :)

**Comment by SergeAstapov** [comment]
Maybe @chriskrycho could help land this one and another small fix #123?

**Comment by chriskrycho** [comment]
I'll take a look at these on Monday!

**Review by chriskrycho — APPROVED** [review]
Ah, this is trivial and easy. :shipit:

**Comment by chriskrycho** [comment]
(Will merge when CI is ✅)

**Comment by chriskrycho** [comment]
Released in [v3.1.0](https://github.com/ember-modifier/ember-modifier/releases/tag/v3.1.0).

**Pull request merged**
