### PR TITLE
WIP: TypeScript conversion

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Related: https://github.com/ember-modifier/ember-modifier/issues/8

This is less straightforward than I thought :(

### CODE REVIEW

**Comment by richard-viney** [comment]
What was the challenge with bringing the types across?

**Comment by NullVoxPopuli** [comment]
@richard-viney mostly dealing with lifecycles, where things like `this.element`  and `this.args` are available at different times. @chriskrycho was also taking a stab at this -- not sure where progress landed though

**Comment by chriskrycho** [comment]
Everything is done except needing to do some polish and fixing a couple curious test issues I ran into. Will probably have a PR up finishing it in the next couple weeks.

**Comment by makepanic** [comment]
Is there anything one can do to help with this PR?

I saw that ember-class-based-modifier is deprecated and tried to migrate to ember-modifier.

**Comment by chriskrycho** [comment]
Apologies; this slipped my mind with other stuff late in 2019. I’ll make a point to get it across the line in the next two weeks (it’s about 95% done!).

**Comment by chriskrycho** [comment]
Aaaand let’s call it one more week: I have this coming Friday dedicated to open source work, so I’ll finish this up then!

**Comment by chriskrycho** [comment]
To my great distress the work-in-progress I had for it seems to have gotten lost. 😢 I'll still probably finish this on Friday (tomorrow), as it wasn't hard and I did nearly all of it on a short plane flight the I did it the first time around.

**Comment by chriskrycho** [comment]
Unfortunately, I spent all day today drafting an Ember RFC, so this fell off my plate. Next week!

**Comment by elwayman02** [comment]
👋 @chriskrycho ❤️

**Comment by chriskrycho** [comment]
Yes! If not sooner, then the week of EmberConf this should get done!

**Comment by azhiv** [comment]
@chriskrycho Any luck?

**Comment by chriskrycho** [comment]
@azhiv apologies for the long delay, but I actually have very good reason to think I'll get to this next week: I have regular, ongoing, dedicated time to work on TS ecosystem concerns now, so once I'm back from vacation (all this week), this is very much on the top of my list, not least because we have a bunch of folks in the app I work on who would benefit from types for this!

**Comment by chriskrycho** [comment]
All, see #23!

**Comment by chriskrycho** [comment]
And thanks @NullVoxPopuli for getting this started originally!

**Pull request closed without merging**
