### PR TITLE
Use release-it and lerna-changelog to manage releases

### PR DESCRIPTION
**Pull request by elwayman02**

### CODE REVIEW

**Comment by elwayman02** [comment]
Will address #14 once a release it cut

**Comment by pzuraq** [comment]
Just a quick update, I'm planning on merging this, but looks like tests are failing due to end of life for older Node versions, so we may need to get ready for a major first. Just haven't had time to dig in

**Comment by rwjblue** [comment]
Updated to use latest `npx create-rwjblue-release-it-setup` result, and rebased. Now that Node < 10 support is dropped this should be good to go.

**Comment by elwayman02** [comment]
Thank you @rwjblue!

**Pull request merged**
